### ISSUE TITLE
Sidebar footer - LoginDisplay - jméno přihlášeného uživatele + iniciály

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#10]
Dole v sidebaru se zobrazuje komponenta LoginDisplay, která má zobrazovat jméno přihlášeného uživatele a jeho iniciály/avatar.

Jméno se tam nyní zobrazuje z claimu "nickname", který není nejvhodnější.
Lepší bude použít claim "name", nebo přímo `User?.Identity?.Name`
Viz stránka `/diag/info` ve spuštěném projektu, kde se zobrazují všechny claimy a informace o uživateli.
Ve zdrojvém kódu DiagnosticInfo.razor je vidět, jak se tam na jednotlivé věci přistupuje.

Taky se tam zobrazuje kolečko s iniciály uživatele. Nyní je tam hardcodováno "DC".
Udělej metodu (ideálně i s unit-testy), která ze jména uživatele sestaví jeho iniciály a použije je tam místo toho.

Alternativně, pokud si troufneš, je možné z AAD získat i avatar uživatele, který by se tam místo toho kolečka s iniciály dal zobrazit (to ale můžeme dodělat i kdykoliv později).

Před implementací tohoto tasku se může hodit mít hotové #2, ale není to úplně podmínkou User.Identity.Name by mělo chodit i nyní (akorát tam stávající implementace s IdentityServerem dává e-mail, takže je to komplikovanější na iniciály).

**Comment by VojtaT04** [comment]
TODO: Unit-testy

**Comment by hakenr** [comment]
@VojtaT04 Zkus si tam udělat unit-test, když do té metody bude vstupovat `null`.
Sice to voláme "opatrně" jako `NameToInitials(@context.User?.Identity?.Name)`, ale ta metoda samotná na `null` spadne, myslím.
Je to výjimečný scénář, ale zas je to triviální mít pokryté, že to bude vracet třeba `String.Empty`, nebo `null`, nebo `"?"`.

**Comment by VojtaT04** [comment]
Jasné, opravím. Nečekal jsem, že by to mohlo na null skončit, ale je pravda, že mě nezabije to tam přidat. Zkusil bych i ty Unit testy, ale asi bych potřeboval nějaký základní tutorial, jak to dostat do toho projektu, aby se to proti nim kontrolovalo.

**Comment by hakenr** [comment]
Přidal jsem #14, tak na to potom můžeš navázat.
V zásadě, abys nemusel testovat celou komponentu, je ideální si testovanou funkčnost vyextrahovat do nějaké service, kterou třeba řešíš i přes dependecy injection.

Tohle je ale spíš jen takový helper, navíc statický, takže ho můžeš testovat i přímo přes:
`var result = LoginDisplay.NameToInitials(input);`

**Comment by hakenr** [comment]
Jinak ještě `string result = "" + someChar + otherChar` není úplně ideální způsob, jak zapsat převod char na string.
Je to takové zakrytí podstaty věci, kdy "zneužíváš" operátor "+", resp. jeho implementaci pro String.

Běžně by se to zapsalo spíš jako
`string result = someChar.ToString() + otherChar.ToString();`
nebo
`string result = (string)someChar + (string)otherChar;`

**Comment by hakenr** [comment]
(Jinak ten zápis z index-operátorem `[^1]` je naopak super, většina řadových .NET programátorů by to tak ani nenapsala, protože je to relativně novinka ze C# verze 8.0)

**Comment by hakenr** [comment]
@VojtaT04,
dobrá práce, ty unit-testy. Pokud bys chtěl být perfekcionista, tak bych tam přidal test na `String.Empty`.
