### ISSUE TITLE
StudentPicker - předělat z HxSelect na HxAutosuggest

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#101]
jak je to podle křestních jmen, špatně se s tím pracuje

**Comment by Xopabyteh** [comment]
@Tob028 @HonbraDev Nechtěli by jste to zkusit? Dokumentace ke komponentě je [zde](https://havit.blazor.eu/components/HxAutosuggest)

**Comment by hakenr** [comment]
Tady je vidět ukázka implementace, nastavím vám přístup do cílové repository: https://github.com/havit/GoranG3/blob/master/Web.Client/Components/Pickers/ContactPicker.cs
