### ISSUE TITLE
Exception on invalid subject id

### ISSUE THREAD

**Issue by SvizelPritula** [mensagymnazium/IntranetGen3#107]
Při pokusu o přístup k neexistujícímu předmětu je vyvolána výjimka místo zobrazení stránky *Stránka nenalezena*.

Příklad: https://intranet.mensagymnazium.cz/electives/subjects/-1

**Comment by hakenr** [comment]
Nedávno jsem to někomu vysvětloval:
> Náš ServerExceptionsGrpcServerInterceptor specificky reaguje na výjimku ObjectNotFoundException.
https://github.com/havit/Havit.Blazor/blob/3b87b4d606657eb768bfb5b08da4b97dd1fb92d4/Havit.Blazor.Grpc.Server/ServerExceptions/ServerExceptionsGrpcServerInterceptor.cs#L36-L40
Sice to pochází z našeho Havit.Data.Patterns.Exceptions.ObjectNotFoundException, ale detekce zámerně probíhá na krátký název typu, takže pokud si vytvoříte kdekoliv vlastní třídu ObjectNotFoundException a budete to používat pro signalizaci, tak ten intercerptor to bude pro gRPC automaticky překládat na gRPC status StatusCode.NotFound a pošle na klienta i exception.Message.
>
>Na klientovi pak takto příchozí gRPC odpovědi [interpretuje náš ServerExceptionsGrpcClientInterceptor](https://github.com/havit/Havit.Blazor/blob/master/Havit.Blazor.Grpc.Client/ServerExceptions/ServerExceptionsGrpcClientInterceptor.cs). Specifické chování pro StatusCode.NotFound v něm ale nemáme, takže by se to dalo chytat obecně ve volajícím kódu takto (my to obvykle nechytáme, snažíme se mít aplikaci uspořádanou tak, aby se to na nexistující věci neodkazovalo, takže to jsou scénáře typu "v mailu mám odkaz na smazaný objekt"):
```csharp
try
{
  var result = XyFacade.MyMethod(...);
}
catch (RpcException ex) when (ex.Status.StatusCode == StatusCode.NotFound)
{
  // ...
}
```
> Jinak přes DI se dá zaregistrovat i IServerExceptionGrpcClientListener, který pak může na klientovi ty výjimky logovat, nebo dělat přesměrování na nějakou 404 stránku, nebo cokoliv potřebuješ.
