### ISSUE TITLE
Změna pravidla pro maturitní semináře z oblastí Člověk a společnost nebo Člověk a příroda

### ISSUE THREAD

**Issue by MartinT1** [mensagymnazium/IntranetGen3#109]
Byl jsem za paní ředitelkou a domluvil jsem, že by se pravidlo dvou maturitních seminářů z oblastí Člověk a společnost nebo Člověk a příroda mohlo rozdělit na pravidla dvě. To by dovolilo studentům si vybrat maturitní semináře, které nejsou z těchto oblastí a zákonný požadavek na tyto obory splnit jinými volitelnými předměty. Bohužel již není moc času, tato změna by musela být hotova do příštího pátku (20.05.2022) před otevřením systému pro celou školu. Také je tu druhý termín příštího pondělí (16.05.2022) kdy pan učitel Hanko chce do systému vepsat všechny předměty na příští rok, potom si budeme muset dávat pozor, abychom s těmi daty nic neudělali. Tato změna by byla pro spoustu studentů docela užitečná (hlavně pro docela velké množství studentů co chtějí předměty jako Maturitní matematika a Maturitní literatura, ale zároveň neplánují maturovat z jiných předmětů), ale vedení na ní nestojí, takže pokud to nestihneme implementovat, tak to nevadí a může to zůstat tak jak je.

**Comment by MartinT1** [comment]
Bavil jsem se s Benjaminem a došli jsme k závěru, že nejjednodušší způsob, jak této změny dosáhnout, by bylo změnit SigningRules na něco, co jen nese informaci o tom, kolik seminářů si musí jaká třída zapsat, a umožňovat to, a vytvořit nový systém, který bude na pozadí kontrolovat, zda zápisy splňují pravidla (jako dva maturitní semináře, seminář z oblastí Člověk a společnost nebo Člověk a příroda, nadstavbový seminář nebo cizí jazyk) a ideálně oznamoval uživateli, když je nesplňuje.

**Comment by Xopabyteh** [comment]
A tak se i stalo :-)
