### ISSUE TITLE
Přihlašování na Safari nefunguje

### ISSUE THREAD

**Issue by Tob028** [mensagymnazium/IntranetGen3#110]
![image](https://user-images.githubusercontent.com/84775852/169647419-10ff0694-6ba4-456f-8cfe-2a54e9ba1487.png)

Jen se načítá a nikdy se nenačte. Nefunguje na telefonu.

**Comment by hakenr** [comment]
@Tob028 Občas se mi to taky stane, nejenom na Safari, ale zatím vždycky pomohl refresh stránky. Zatím jsem tomu nevěnoval větší pozornost, zkusím se příště podívat pozorněji, co se tam děje.
