### ISSUE TITLE
Vracení z náhledu předmětu - pamatovat si nastavení filtru a řazení seznamu předmětů

### ISSUE THREAD

**Issue by VojtaT04** [mensagymnazium/IntranetGen3#111]
Při kliknutí na tlačítko zpátky při náhladu předmětu se tabulka předmětů zobrazí od začátku. Lepší by bylo, aby zůstala na místě, kde byl člověk předtím. Problém to je převážně na mobilu, kde je pak potřeba hodně scrollovat.

*Z feedbacku ze Septimy*

**Comment by VojtaT04** [comment]
První krok by mohlo být pamatovat si alespoň, jak byla tabulka řazená, což seteď neděje (vrací se na defaultní řazení podle názvu předmětu)

**Comment by hakenr** [comment]
Je potřeba si někam (třeba do singleton služby nebo do static fieldu komponenty) příslušná nastavení pamatovat a při příchodu na stránku je z tohoto uložiště obnovit.

**Comment by Xopabyteh** [comment]
Teď si to pamatuje filtr, ještě chybí zapamatovat si řazení. Na HxGrid jsem neobjevil API, kterým bych řazení nastavil z venku.
Taky se to vizuálně chová trochu zvláštně. Když udělám tyhle kroky:
1. Načte se mi `s_rememberedSubjectListFilter` v `OnInitialized()`
2. Nastavím nový filtr pomocí `GradePicker` v `SearchTemplate`
Tak se filter updatuje, ale neupdatujou se chipy `HxListLayout`, takže v `SearchTemplate` vidím _Kvarta_, ale v chipech `HxListLayout` vidím _Septima_.

* Ten chip se updatne když jdu znova na jinou stránku a nazpět (znovu se přenačte filter v `OnInitialized()`)
* Chip vznikne až když se načte filtr v `OnInitialized()`, pokud změním filter pomocí SearchTemplate, tak se chip neobjeví.

cc @hakenr

**Comment by hakenr** [comment]
@Xopabyteh Vyhoď filtr na Grade z toho offcanvas filtru, nech ho jenom v SearchTemplate, neměl by být v obojím.

Co se řazení týče (spíš bych se na něj vykašlal, ale budiž), tak to se nastavuje skrze manipulaci `CurrentUserState` parametru na gridu (musíš si ho `@bind-CurrentUserState` vytáhnout do fieldu).
