### ISSUE TITLE
Odhlášení 

### ISSUE THREAD

**Issue by koli22** [mensagymnazium/IntranetGen3#118]
V pondělí 20. 3. jsem se hned v minutu otevření přihlašování přihlásil na přednášky. Pak, když jsem si večer kontroloval, jestli jsem přihlášen, kde chci, tak jsem ještě všude přihlášen byl. Ale dnes (21. 3.) Ráno jsem se ještě jednou koukal na svoje přihlášky a zjistil jsem, že mi zmizela přihláška na přednášku od Koviho a nemohu se znova přihlásit.

**Comment by hakenr** [comment]
@koli22 Tvojí registraci na přednášku vidím v DB jako zrušenou ve 2023-03-20 23:35:41.5244759.
Jestli sis to nezrušil sám, pak to musel udělat někdo z organizátorů fóra. Ti mají k takové operaci oprávnění.
