### ISSUE TITLE
[MensaForum] Problém se zrušením + přihlášené se neoznačují zeleně

### ISSUE THREAD

**Issue by PeculiarCreature** [mensagymnazium/IntranetGen3#121]
Trochu jako bych nebyla přihlášená, ale přihlášená jsem. Potřebovala bych si ale zrušit některé přednášky a nejde to (neobjevuje se tlačítko).
- K. Jendelová (oktáva)

**Comment by hakenr** [comment]
Cherry-picknul jsem to do `mensaforum` branch
