### ISSUE TITLE
Migrace do .NET8

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#125]
Je potřeba zmigrovat projekty z .NET7 do .NET8.

Updatovat NUGET balíčky.

Možná bude potřeba migrovat i HX Komponenty: https://havit.blazor.eu/migrating

**Comment by hakenr** [comment]
@JStrm vidím branch, uznávám úkol za splněný.
(Nakonec jsem to dotáhnul i s upgradem Havit knihoven, což už nebylo tak triviální.)
