### ISSUE TITLE
SubjectList - automaticky použít filtr na ročník (UX)

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#126]
Filtr už existuje, bylo by dobré ho rovnou aplikovat, pokud je uživatel student.

**Comment by Xopabyteh** [comment]
Když jsem nastavil filter v OnInitializedAsync, tak se sice aplikoval, ale neprojevil se v UI `HxListLayout` (nebyly vidět chipy a to menu, kde se filtr nastavuje, bylo prázdné)

Na `HxFilterForm` jsem objevil metodu `UpdateModelAsync()`, ale na `HxListLayout` už jsem nic podobného nenašel.

cc @hakenr

**Comment by hakenr** [comment]
Myslel jsem, že bychom to udělali mimo HxOffcanvas jako stálý filtr přímo viditelný na SubjectList, jako to bylo v minulých letech (jenom to nabízelo zápisová pravidla místo ročníku):
![image](https://github.com/mensagymnazium/IntranetGen3/assets/12828888/10320fea-0bf5-4988-a628-2f442a1428ea)

...čistě jako rychlý filtr, který studentovi zobrazí předměty, z kterých vůbec může vybírat.

Na to by nemělo být potřeba řešit chipy a tyhle komplikace kolem. Stačí se podívat, jak to bylo uděláno dříve, viz třeba zde:

https://github.com/mensagymnazium/IntranetGen3/blob/61103be0179d180311c77dcf12e2a59b66effd4c/Web.Client/Pages/Electives/SubjectList.razor#L10-L17

https://github.com/mensagymnazium/IntranetGen3/blob/61103be0179d180311c77dcf12e2a59b66effd4c/Web.Client/Pages/Electives/SubjectList.razor.cs#L91-L96

Jenom dneska už není potřeba rozklad na parametry `Value`, `ValueChanged` a `ValueExpression`, ale používá se to v nové syntaxi takto:
```razor
<GradePicker @bind-Value="subjectListFilter.GradeId" @bind-Value:after="HandleGradeFilterChanged" />
```
a
```csharp
 private async Task HandleGradeFilterChanged() 
 { 
 	LastGradeId = subjectListFilter.GradeId; 
 	await subjectsGrid.RefreshDataAsync(); 
 } 
```
