### ISSUE TITLE
Subject - Přidat: ke které profilové maturitě předmět vede

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#130]
Zatím nejspíš bude stačit nějaký jednoduchý `Enum maturitních předmětů`/`Enum maturitních oborů` a předmět na sobě bude mít, ke kterému maturitnímu předmětu/oboru vede (nebo null, pokud k žádnému).

**Comment by hakenr** [comment]
@Xopabyteh Ještě bych zvážil, jestli nemůže vést k více než jednomu maturitnímu předmětu.

**Comment by Slavek592** [comment]
Hotovo (připraveno na validaci)
