### ISSUE TITLE
Validace - Vzdělávací oblasti

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#133]
Podle [pravidel pro zápis volitelných předmětů](https://mensagym.sharepoint.com/sites/eqwrfsdqwreada/Sdilene%20dokumenty/General/VOLITELN%C3%89%20P%C5%98EDM%C4%9ATY%20-%20podm%C3%ADnky%20pro%20jednotliv%C3%A9%20ro%C4%8Dn%C3%ADky%2020223024.pdf?OR=teams) si student septima a výš musí rozdělit předměty, aby spadali do spadali do vzdělávací oblasti. 

Vzdělávací oblast je teď v modelu označená jako `SubjectType.cs` (jsem pro přejmenování ;) )

Podobně jako v #132 nebo #131 by měla vzniknout nějaká service, která bude říkat, jestli je podmínka splněna a potom bude vracet ano/ne a seznam chybějcích požadavků.

**Comment by hakenr** [comment]
Souhlasím s přejmenováním, název byl převzatý z IntranetGen2.
Jaký název navrhuješ?

**Comment by Xopabyteh** [comment]
Něco jako `StudyField` nebo `EducationalArea`

**Comment by hakenr** [comment]
`EducationalArea` se mi líbí.
