### ISSUE TITLE
SubjectRegistrationsManagerService - Kontrola, jestli předměty nekolidují v rozvrhu

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#138]
Registrované předměty by neměli kolidovat.

Tohle bude asi o něco těžší, protože kromě klasických předmětů 14:30 - 17:50 v jeden den jsou i jazyky, které jsou vícekrát v týdnu a předměty jako matfyz, který je někdy v 7 ráno. 

Nejspíš bude potřeba předtím upravit model, aby takovou logiku vůbec dovedl zachytit.

**Comment by hakenr** [comment]
Toto myslím už loňská podoba dělala, minimálně v nějaké zjednodušené podobě, ale jist si nejsem.
Nebo se to minimálně diskutovalo (Nedošli jsme k závěru, že se to nechce, protože paní ředitelka s časy ještě hýbe? Možná by to mohla být soft-validace - varování, ale neblokovat.)

**Comment by hakenr** [comment]
Jazyky bych úplně neřešil, pro začátek bych to formuloval jako "varovat před kolizí spočívající ve dvou předmětech se stejným nastavením začátku (slotu)".
