### ISSUE TITLE
Build - Opravit selhávající buildy při commitu

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#143]
Vypadá to, že selhávají jenom na pár convention warnings, ale warning = error.

**Comment by hakenr** [comment]
@Xopabyteh Tohle doporučuji nevypínat globálně, ale nastavit pro příslušné properties výjimku v konfiguraci entity.
Viz https://github.com/havit/GoranG3/blob/master/Entity/Configurations/Projects/ProjectConfiguration.cs#L17
```csharp
namespace Havit.GoranG3.Entity.Configurations.Projects;

public class ProjectConfiguration : IEntityTypeConfiguration<Project>
{
	public void Configure(EntityTypeBuilder<Project> builder)
	{
		...
		builder.Property(e => e.MigrationId).SuppressModelValidatorRule(ModelValidatorRule.OnlyForeignKeyPropertiesCanEndWithId);
	}
}
```
