### ISSUE TITLE
Doplnit konfiguraci entit - výjimky z pravidla `CheckOnlyForeignKeysEndWithId` (test `IntranetGen3DbContext_CheckModelConventions`)

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#145]
Teď je v testu jedno pravidlo vynecháno: `CheckOnlyForeignKeysEndWithId`.

Aby se uplatnilo, bude potřeba přejmenovat pár parametrů v modelu. A pak samozřejmě výjimku z testu odebrat.

**Comment by hakenr** [comment]
Nepřejmenovával bych to, jen nastavíme ty výjimky na properties v EntityConfiguration.
