### ISSUE TITLE
GradeRegistrationCriteria - Vyrobit editační komponentu

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#147]
Prakticky to samé jako `SubjectEdit`. Měla by umožnit Administrátorovi změnit konfiguraci kritérií pro daný ročník.

**Comment by hakenr** [comment]
Úplně původně jsem myslel, že všechny ty parametry budeme hardcodovat, ale pak do toho začaly prosakovat parametry typu "počet hodin", tak nevim.
Nechme tomu volný průběh, jestli to tedy uhrajeme na nějaké grade-specific konfiguraci, nebo se vrátíme k původní myšlence.

**Comment by Xopabyteh** [comment]
Přišlo mi to jako taková střední cesta, to pravidlo je hardcoded v té validaci, a tady jsou jeho parametry, ale neimplementoval jsem to moc hloubky, dá se to jednoduše segregovat do nějakého switche.

Chtel jsem se o tom pobavit v úterý, ale teď koukám, že v úterý je volno a příští úterý jsou myslím projektové dny, takže to nejspíš budeme muset vyřešit tady
