### ISSUE TITLE
SubjectRegistrationProgressValidationService.GetRegistrationProgressOfStudentAsync() - Co když metodu volá oktaván? 

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#155]
Asi by to mělo být zajištěno i tak, že oktaván tu metodu volat nebude, ale teď to studentům z oktávy způsobuje krach, protože je volaná z `HomeIndexMyElectives.razor`

**Comment by hakenr** [comment]
Stejnětak to padá "nestudentům" (učitel, admin, ...).
Je potřeba tam dát podmínku "komu se to má kontrolovat" (nikoliv "komu se to nemá", to se hůře udržuje).

**Comment by Xopabyteh** [comment]
@RiMiDo420  Teď už to padá jenom studentům oktávy. Logika, kterou lze získat třídu přihlášeného studenta je vidět třeba v `SubjectList.razor.cs`:

```cs
if ((await ClientAuthService.GetCurrentClaimsPrincipal()).IsInRole(nameof(Role.Student)))
{
	// Get grade (shouldn't be null, user is student)
	var gradeId = await ClientAuthService.GetCurrentStudentGradeIdAsync();
	Debug.Assert(gradeId != null, nameof(gradeId) + " != null");

	// Determine "rocnikovka warning"
	showRocnikovkaWarning = (gradeId == GradeEntry.Kvinta || gradeId == GradeEntry.Sexta);
}
```

**Comment by hakenr** [comment]
Já jsem tam zatím dal nějakou `OperationFailedException`, ale ještě to doladím, aby to bylo nějak neškodné.

**Comment by hakenr** [comment]
Jinak bych šel cestou, kdy oktavánům sekci Volitelné předměty v sidebaru vůbec nezobrazíme a stejnětak na homepage nebudeme zobrazovat tu komponentu s přehledem stavu zápisů.

Docela by se na to hodila AuthorizationPolicy:
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0#role-based-and-policy-based-authorization
https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-8.0
https://github.com/havit/GoranG3/blob/89e5d0f748b910a0227c92df5ed39da4793d98e6/Web.Client/Program.cs#L171-L174
