### ISSUE TITLE
Terminologie: "Dotované hodiny" => "hodiny", "hodin týdně", atp.

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#157]
Asi bych se raději vyhnul pojmu "dotované hodiny", "hodinová dotace" apod. Je to zbytečně matoucí a nejsem si ani jist, jestli to používáme správně.

Nechal bych všude jen "hodiny", "počet hodin", "hodin týdně" atp., např. kde se motáme kolem `HoursPerWeek`, ale i jinde.

Předmětem tohoto tasku je tedy úprava UI-textů v aplikaci.
Namátkou to vidím v:
* `SubjectEdit`
* `SubjectDto` - validace
* `HomeIndexMyElectives.razor`
* `SubjectDetail`
* ...možná to bude ještě někde (Ctrl + Shift + F = Find in files)

cc @Xopabyteh

**Comment by Xopabyteh** [comment]
Má cenu to měnit i v aplikační logice? Když to necháme v UI jako `hodiny týdně` a v aplikaci jako `Dotované hodiny`, nevzniká v tom potom chaos?

cc @hakenr

**Comment by hakenr** [comment]
@Xopabyteh Jo, všiml jsem si, že to proniklo i do názvů properties a metod. Ideálně bych to vyházel všude a držel se `HoursPerWeek` nebo jen `Hours` dle kontextu. Ale nespěchá to.
