### ISSUE TITLE
Soubor, jenž sem určitě nepatří: Kepler - logo

### ISSUE THREAD

**Issue by Slavek592** [mensagymnazium/IntranetGen3#162]
Mám takovou neobvyklou otázku... Za jakým účelem je tady [obrázek loga Keplera](https://github.com/mensagymnazium/IntranetGen3/blob/master/Web.Client/wwwroot/Kepler.png)? Myslím, že to je dostatečně velké "issue", aby se tím někdo zabýval. :)

**Comment by Xopabyteh** [comment]
Zničit prosím :heart:

**Comment by hakenr** [comment]
(To tam zůstalo z úplně původních hrátek, kdy to někdo tuším měl na 404 error page, nebo pro něco takového.)
