### ISSUE TITLE
DATA: Jazyk je potřeba povolit všem ročníkům

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#172]
Na rozdíl od předchozích let se nyní jazyk zapisuje i v kvartě a výše. Je potřeba mu tedy povolit všechny ročníky.

**Comment by Xopabyteh** [comment]
Nechal bych naklikat všechny třídy toho, kdo bude zapisovat ty předměty. Takže pan Hanko?

**Comment by hakenr** [comment]
Ano, už jsem si to poznamenal do instrukcí pro obsluhu, issue zavírám.
