### ISSUE TITLE
StudentSubjectRegistrationComponent - IsRegistrationPossible nedovolí zapsat jazyk jako poslední

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#173]
Pokud si nechám zápis jazyka jako posledního, mám splněné hodiny a podmínka v `IsRegistrationPossible` už mi jazyk nedovolí zapsat:
![image](https://github.com/mensagymnazium/IntranetGen3/assets/12828888/441f8764-1775-42d9-b6b8-e4df28665276)
![image](https://github.com/mensagymnazium/IntranetGen3/assets/12828888/4d1cce27-5ac5-433f-845e-83c62ff0cd6b)

https://github.com/mensagymnazium/IntranetGen3/blob/222294f8a13f61bf4af88898d315c3449d58e09f/Web.Client/Pages/Electives/StudentSubjectRegistrationComponent.razor.cs#L28-L35

Je potřeba dovolit registraci na jazyk, pokud ještě není zapsán.

cc @Xopabyteh

**Comment by hakenr** [comment]
@Xopabyteh Martine, tenhle commit nejspíš revertuji, je v tom příliš mnoho bodů, které by se měly řešit jinak:

1. Metoda `LoadIsRegistrationePossibleAsync()` obsahuje poměrně zásadní aplikační logiku "Mohu si zapsat předmět X?", která by neměla být takto přilepena v UI, ale mělo by to být nějak u ostatního kódu, který řeší, co si mohu zapsat, jestli splňuji pravidla, atp. 
   * viděl bych to na severovou metodu něco jako `ISubjectRegistrationsManagerFacade.CanRegisterAsync(StudentSubjectRegistrationCreateDto registration, ...)
   * přičemž by to uvnitř používalo `ISubjectRegistrationsManagerService`
   * nejspíš by se hodilo vyextrahovat ty testy z `ISubjectRegistrationsManagerFacade.CreateRegistrationAsync(...)` a používat stejnou ověřovací logiku i pro `CanRegisterAsync(...)`
   * ...prostě nějak tímto směrem (logiku na server, maximálně centralizovat, maximální reusovat, DRY, KISS)
2. `SubjectCategoryDto.DtoEntry` - pokud je potřeba jakékoliv _Entry_ používat i ve `Web.Client`, tak se přresune z `Model` do `Primitives` projektu (viz `GradeEntry`, které už tam je). Výjimka jsou entries, které nemají pevná ID, ale to není tento případ.
3. Blazor syntaxe
    ```diff
    -            OnClick="() => HandleCancelRegistrationClicked()"
    +            OnClick="async () => await HandleCancelRegistrationClicked()"
    ```
    ve skutečnosti to je
    ```razor
    OnClick="HandleCancelRegistrationClicked"
    ```
    ...pokud to nemá parametry, není potřeba to komplikovat.
4. Přidání `[Parameter] public SubjectDto Subject { get; set; }` k existujícímu `[Parameter] public int? SubjectId { get; set; }`, nedává moc smysl. Je to druhý parametr, který nese prakticky stejný význam. Pokud implementujeme správně bod 1., nebude to potřeba. (Nicméně v budoucnu, kdybys někdy potřeboval, volí se jen jedno z toho. Zde třeba `SubjectId` a pak třeba `SubjectsDataStore` a z něj si dle ID vyzvednout data.

...zkus na to mrknout, kdyžtak můžeme spolu.

**Comment by Xopabyteh** [comment]
Ještě dneska se na to podívám a vyrobím pull request, pochopil jsem co a jak

**Comment by hakenr** [comment]
I jsem to trochu zkoušel na preview a přijde mi to funkční.
