### ISSUE TITLE
Nadstavbový seminář?

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#174]
@Xopabyteh Nějak jsem se ztratil v podmínce na "nadstavbový seminář" (dvouletý, kvarta + kvinta).
Pamatuji si správně, že pan Brdek už toto nepotřebuje rozlišovat a v PDF podmínkách to zůstalo jen setrvačností?
...jestli to ve finále není podmínka, kterou bychom měli přidat.

**Comment by Xopabyteh** [comment]
Z těch schůzek jsem pochopil, že ty nadstavbové semináře se zapisují na 2 roky. To s tím, že předměty mohou být nadstavbové pro kombinaci ročníků (kvinta, sexta) tam vidím poprvé. Nevím, jestli takovou logiku stihneme vyrobit, ale ta registrace by tím pádem měl nést hodnotu, jestli je specializační/nadstavbová, což by si vybral student při zápisu (pokud má na výběr).

To bychom pak využili příští rok, kdy budeme implementovat to pamatování registrací.

**Comment by Xopabyteh** [comment]
Pro teď řešit jenom ukazováním warningu pro kvintu/sextu u předmětu v `registrační komponentě` a nejspíš i někde na `subjectlistu`, něco ve stylu: "Předmět si lze zvolit jako nadstavbový, **je potřeba explicitní domluva s vedením**". I předmětů, jejichž `subjectcategory` je `extension seminar` to asi ani není potřeba, _ale neukázat to je víc práce než to ukázat_

**Comment by hakenr** [comment]
> I předmětů, jejichž `subjectcategory` je `extension seminar` to asi ani není potřeba, _ale neukázat to je víc práce než to ukázat_

Zase nechceme, aby se chodili ptát i na ty nadstavbové předměty.
Ale může to být i o textu hlášky, aby se to výstižně popsalo.

Něco jako
_Upozorňujeme studenty kvarty a kvinty, že pro kvintu a sextu je potřeba zvolit jeden dvouletý nadstavbový seminář. Po předchozí dohodě s vedením školy lze jako nadstavbový seminář zapsat i jakýkoliv jiný typ semináře._
