### ISSUE TITLE
SubjectDataSeed - Předměty (DemoProfile)

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#19]
Aby se dala aplikace snadno vyvíjet a předvádět, potřebujeme ji naplnit ukázkovými daty - pro začátek předmětů. Hodnoty vezměme z IntranetGen2, vystavím někde podobu její databáze.

Instrukce: [Seedování dat](https://github.com/mensagymnazium/IntranetGen3/blob/master/doc/DataSeeds.md)

Data původního IntranetGen2 jsem připravil zde:

https://teams.microsoft.com/l/message/19:1a86a91777df40a792f5e1232699cf4e@thread.tacv2/1634807487521?tenantId=bc4facfa-6ca4-4771-aa06-3bce0418701c&groupId=3ce83c1f-7360-48d6-89f5-82a93ef86696&parentMessageId=1634807487521&teamName=SemPrg2&channelName=Intranet&createdTime=1634807487521

Je tam pár rozdílů, které bude potřeba překonat:
* v původní DB není z předmětu odkaz na učitele, ale je tam jen textový atribut pro jméno učitele (to bych rád udělal strong-type odkaz na instanci entity `Teacher`)
* podobně je to s rozvrhem, je tam Day (den v týdnu) a Period (výukový blok ve dni), to bych asi zachoval, resp. ty hodnoty Period bych přepočítal na číslo počáteční hodiny, tj. 1 (8:30), 3 (10:15), 5, 7, 9, ... Nyní je tam myslím 1, 2, 3, 4, ...

Nejprve je potřeba připravit  #8 - datový model Předmětů.

**Comment by hakenr** [comment]
@VojtaT04 Přehlídli jsme to, ale učitelé jsou tam už naseedovaní...
![image](https://user-images.githubusercontent.com/12828888/141372034-f4290574-b56d-408e-ad7f-2cbec7f035fa.png)

**Comment by VojtaT04** [comment]
TODO: SubjectType + SubjectSubjectCategory

**Comment by hakenr** [comment]
@VojtaT04 SubjectDataSeed jsem zkonsolidoval, doplnil seedování typů, kategorií, učitelů i ročníků.
Zvaž, jestli to přecijenom nenaplnit reálnými (loňskými) daty z výše odkazovaného Excelu, lépe by se to testovalo.
