### ISSUE TITLE
StudentSubjectRegistrations - ověřit, že nezohledňujeme registrace smazaných předmětů

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#191]
Tipuji, že ve validačním kódu a různě, kde si načítáme aktuální registrace studenta, tak nikde nemáme logiku, aby to ignorovalo StudentSubjectRegistrations, které mají smazaný předmět (`ssr.Subject.Deleted != null`).

Potřebujeme docílit toho, že když v polovině zápisového okna vedení školy promaže předměty (třeba o které není zájem a nebudou zjevně vypsány), tak aby se studentům ukázalo, že nemají splněný zápis a dovolilo jim to zapsat předměty jiné.

cc @Xopabyteh (Když se toho do té doby nikdo neujme, tak to nějak o víkendu odbavím.)

**Comment by Xopabyteh** [comment]
Vyzkoušel jsem, se smazáním předmětu se mažou i registrace v databázi. Query, které na tom probíhají pro validaci i pro získávání přihlášených studentů **pracují s nesmazanýmy daty**.

V commitu [df52778](https://github.com/mensagymnazium/IntranetGen3/commit/df527789665b02d118cfd59300ecaeb0e7b5496c) jsem poupravil pár názvů, aby to bylo jasnější. U jednoho přejmenování čekám na odbavení PR #193 , abych nezpůsobil merge conflicty.

Pak close?

**Comment by Xopabyteh** [comment]
Přejmenováno a otestováno
