### ISSUE TITLE
TeacherSeed - doplnit User.Lastname

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#199]
Už je to doplněno do StudentSeed, ještě je potřeba TeacherSeed. (Sice to už reálně nepoužíváme, ale ať je to korektní).

**Comment by hakenr** [comment]
@Xopabyteh ...nějaké tasky, obzvláště Easy, je potřeba nechat taky ostatním studentům SemPrgX :-D

**Comment by Xopabyteh** [comment]
Dobře, na label Easy už nešahám :D
