### ISSUE TITLE
SubjectList - Mazání ve správě seznamu předmětů

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#26]
Navazuje na #11 - SubjectList.
Do seznamu předmětů bude potřeba přidat jejich mazání (z kontextového menu).
Předloha:
* https://github.com/hakenr/GoranG3/blob/master/Web.Client/Pages/Admin/CurrencyList.razor
* https://github.com/hakenr/GoranG3/blob/master/Web.Client/Pages/Admin/CurrencyList.razor.cs

Bude potřeba rozšířit SubjectFacade o mazací metodu, viz předloha:
Viz https://github.com/hakenr/GoranG3/blob/master/Facades/Finance/CurrencyFacade.cs

**Comment by hakenr** [comment]
SubjectList je připraven (kostra), SubjectFacade připravena (kostra), dá se to dělat.

**Comment by Jan-Sliva** [comment]
Udělal jsem mazací metodu do SubjectFacade.
