### ISSUE TITLE
SigningRules - datový model (HOTOVO) + DemoSeed (WIP)

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#49]
Předchozí Intranet pracoval s konfigurovatelnou sadou pravidel pro zapisování předmětů:

https://github.com/mensagymnazium/IntranetGen2/blob/master/MI.Server.DataAccess/DbObjects/Entities/SigningRulesDb.cs

Prozkoumej, jak to fungovalo, připrav datový model a seed dat v DemoProfile - použij loňské údaje, data jsou v Excelu připojeném ve školních Teams.

## Podpůrná dokumentace
[Instrukce: EF Migrace](https://github.com/mensagymnazium/IntranetGen3/blob/master/doc/EF-Migrations.md)
Dokumentace EF Core migrations: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs
Dokumentace HAVIT Stack - EF Core: https://github.com/mensagymnazium/IntranetGen3/blob/master/doc/HAVIT%20Stack/HAVIT%20Stack%20-%20EF%20Core.pdf

**Comment by hakenr** [comment]
@Jan-Sliva, zkonsolidoval jsem to trochu, aby to odpovídalo businessovým požadavkům. Podívej se do toho dumpu databáze stávajícího intranetu - ono je potřeba, aby šlo nastavit třeba pravidla:
1. musí si nastavit jeden předmět typu Jazyk a jazyková komunikace ze skupiny Cizí jazyk"
2. a k tomu si musí nastavit druhý předmět libovolného typu ze skupin A nebo B
3. a k tomu si musí nastavit třetí předmět typu A nebo B ze skupin D nebo C.

Mrkni na to, viz poslední commit, taky jsem tam udělal rovnou migraci DB.
Už tam zbývá jen udělat nějaký ten seed dat.

**Comment by Jan-Sliva** [comment]
Přidal jsem Name a Descritpion, teď pracuji na DemoSeedu

**Comment by hakenr** [comment]
@Jan-Sliva, zkonsolidoval jsem to do SigningRuleSeed (vč. categories a types) a zbývá tam jen doplnit pravidla pro vyšší ročníky.

**Comment by Jan-Sliva** [comment]
Hotovo
