### ISSUE TITLE
Branding do sidebaru

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#5]
Aplikační šablona má vlevo sidebar (Sidebar.razor), do kterého je potřeba umístit logo MG a název projektu "Intranet".

Dokumentace: https://havit.blazor.eu/components/HxSidebar

Ukázka: https://github.com/havit/Havit.Blazor/blob/master/Havit.Blazor.Components.Web.Bootstrap.Documentation/Shared/SideBar.razor

**Comment by SvizelPritula** [comment]
Implemented successfully.
