### ISSUE TITLE
SubjectList - Sloupec Kapacita rozšířit o signalizaci obsazenosti předmětů - doladit UI

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#63]
![image](https://user-images.githubusercontent.com/12828888/160217609-ea291718-3dd5-42e4-8cc8-917d53fa262e.png)

Nyní se tam zobrazuje jen celková kapacita předmětu,
rozšířil bych to na podobu "10(+3)/15" (nebo nějakou takovou), kde by bylo
* 10 - počet primárně zapsaných
* +3 - počet zapsaných jako náhradní volba
* 15 - celková kapacita předmětu

První dva údaje bude potřeba brát ze StudentSubjectRegistration (rozšířit výstupní DTO ze SubjectListQuery).

**Comment by hakenr** [comment]
Už je to tam připravený, jen se to vykresluje do UI v jiné podobě.

**Comment by hakenr** [comment]
Docela pěkně mi to přijde udělaný na Mensa forum (tuším od @SvizelPritula), ukazuje to ikonkou zaplněnost.

**Comment by SvizelPritula** [comment]
Done in 855f65b051c058763247a49bcd05e18913a8f01d.
