### ISSUE TITLE
Subject-Edit - učitelům dovolit editovat jen vlastní předmět

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#66]
* nezobrazovat editovací prvky v SubjectDetail
* dovolit měnit učitele předmětu?
* client-side UI + server-side verifikace!

**Comment by hakenr** [comment]
Pro letošní ročník domluveno, že zatím editace bude jen pro adminy.

**Comment by Xopabyteh** [comment]
@KLEP37 Nechtěl by jsi to zkusit?
