### ISSUE TITLE
Datový model - Předměty

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#8]
Potřebujeme ustavit datový model pro přeměty (entity do projektu Model, EF Core migraci do projektu Entity a vygenerovat datovou vrstvu pomocí code-generatoru do projektu DataLayer).

Inspirací nám může být datový model předmětů z předchozí verze intranetu:
https://github.com/mensagymnazium/IntranetGen2/tree/master/MI.Server.DataAccess/DbObjects
* zejména je tam zřejmé, jaká data můžeme převzít k předmětům ze stávající databáze (budeme migrovat)
https://github.com/mensagymnazium/IntranetGen2/blob/master/MI.Server.DataAccess/DbObjects/Entities/SubjectDb.cs

## Podpůrná dokumentace
* [Instrukce: EF Migrace](https://github.com/mensagymnazium/IntranetGen3/blob/master/doc/EF-Migrations.md)
* Dokumentace EF Core migrations: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs
* Dokumentace HAVIT Stack - EF Core: https://github.com/mensagymnazium/IntranetGen3/blob/master/doc/HAVIT%20Stack/HAVIT%20Stack%20-%20EF%20Core.pdf

**Comment by hakenr** [comment]
Závislé na #6, které musí být nejprve hotovo.

**Comment by hakenr** [comment]
Udělal jsem tam základní migraci (+ vygeneroval DataLayer), aby se na to už dalo navazovat dalšími tasky.
Pokračuj dle výše uvedeného, úpravy budeš potřebovat stejně završit migrací.

Jinak ukázku M:N vazby najdeš zde https://github.com/hakenr/GoranG3/tree/master/Model/Security
Vazebními entitami jsou zde `UserGroupMembership` (M:N mezi `User` a `UserGroup`)
a `UserGroupRole` (M:N mezi `UserGroup` a `Role`).

Ještě k tomu bude potřeba konfigurace té vazby, to může vypadat nějak takto:
https://github.com/hakenr/GoranG3/blob/master/Entity/Configurations/Security/UserGroupMembershipConfiguration.cs
(asi nebudeš dělat kolekci ze směru `Grade`, že by tam bylo `Grade.Subjects`, takže to může být jen z jednoho směru `Subject.Grades` ála
https://github.com/hakenr/GoranG3/blob/master/Entity/Configurations/Security/UserGroupRoleConfiguration.cs)

Je to trochu tricky. Udělej, uvidíš, kam se dostaneš, rád ti to pomůžu dokončit.

**Comment by SvizelPritula** [comment]
@VeronikaJuzkova Taky se ukazuje, že vazba učitel - předmět je taky many to many.

**Comment by hakenr** [comment]
Potřebujeme tuto část datového modelu přednostně dokončit, navazuje na to většina další práce.
Abychom se posunuli, udělám na tom část práce já.
