### ISSUE TITLE
[Mensaforum] Vyměnit seedy dat

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#86]
Učitelé => Přednášející
Předměty => Přednášky, kapacita max. 37 lidí
Category => udělat jedinou
Group => udělat jedinou

Zápisová pravidla => kvarta, kvinta, sexta, septima; 9 primárních zápisů
* je nutno nastavit jako kvinta až oktáva (systém posunuje rok)
* název pravidla všude "Mensaforum"

**Comment by MartinT1** [comment]
<html>

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>




PONDĚLÍ    8:30-10:00 | 10:15-11:45 | 12:15-13:45
-- | -- | --
  | JAKUB ŽELEZNÝ   Praxe v České televizi | FILIP TUREK   Debata o závodech formule, o sběratelství starých a vzácných aut, o   investicích
  | HALINA ŠIMKOVÁ   Slepá místa kriminalistiky – o chybách forenzní vědy a kauzách, kde   sehrály velkou roli | VLADIMÍR STREJČEK   Ilustrátorství
  | (11:00-12:10)   LENKA BRADÁČOVÁ   Vrchní státní zastupitelství | JAN SKRYJA    Lucidní snění



<p class=MsoNormal><span lang=CS><o:p>&nbsp;</o:p></span></p>


</body>

</html>

**Comment by MartinT1** [comment]
Moc se omlouvám, že jsem to ještě nedodělal, dostal jsem to alespoň do stavu, kde jediné změny jsou textové parametry, a není potřeba nic přidávat a odebírat. Dle mého názoru by to mělo být připravené na základní spuštění. Jména učitelů co nejdříve doplním.

**Comment by hakenr** [comment]
@MartinT1 ještě dodělám SigningRuleSeed, na tom teď padají testy.

**Comment by MartinT1** [comment]
Základ seadů je hotový, je tam spousta záznamů s Placeholder, ale to potom doplním skrz frontend.
