### ISSUE TITLE
[Mensaforum] Nedovolit primární zápis na více předmětů ve stejnou dobu

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#87]

**Comment by SvizelPritula** [comment]
Commit 5044b8a2c81e6846129731724e26b29968c8cb15 tento issue neřeší správně, neboť `subjectStudentRegistrations` obsahuje jenom přihášení na aktuální předmět. Je potřeba z databáze vytáhnout zvlášť všechny přihlášení pro aktuálního uživatele.
