### ISSUE TITLE
[MensaForum] RegistrationEdit padá + není jak vybrat Subject

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#93]

**Comment by VojtaT04** [comment]
To asi taky bude souviset s f9497003032fbf2dc8f415b131401b9250aba35d, zkusím opravit.

**Comment by VojtaT04** [comment]
Funguje, jenom se admini musí smířit s přebývajícími kolonkami "Typ zápisu" a "Zápisové pravidlo".

**Comment by VojtaT04** [comment]
Ověřeno, je to asi tak, ostatní přihlášky tuto chybu nehází. V tu chvílí vlastně asi není chyba v kódu, ale v divném stavu, ve kterém se to teď nachází - vymažu tohle přihlášení a poběží to fajn.
